version: '2'

checks:
  eslint:
    enabled: true
    config: .eslintrc.json
  rubocop:
    enabled: true
    config: .rubocop.yml
  complexity:
    enabled: true
  duplication:
    enabled: true

engines:
  eslint:
    enabled: true
  rubocop:
    enabled: true
  complexity:
    enabled: true
  duplication:
    enabled: true

ratings:
  paths:
    - '**/*.{rb,js,jsx,ts,tsx}'

prepare:
  dependencies:
    override:
      - echo "Installing dependencies..."
      - bundle install
      - npm install

exclude_paths:
  - 'vendor/**/*'
  - 'node_modules/**/*'

ignore_issues:
  - 'ESLint/no-unused-vars'
