name: Push checks
on: [push]
jobs:
  Checkout:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: checks out current branch
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: checks out main branch
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 9.*
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile
      - name: Check linting and formatting
        run: pnpm biome lint $(git diff --name-only $(git merge-base ${{ github.ref_name ${{ github.head_ref }}  ) ${{ github.head_ref }})
      - name: Tests
        run: pnpm test
