name: Push checks
on: [push]
jobs:
  Checkout:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: pnpm/action-setup@v4
        with:
          version: 9.*
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile
      - name: Get file changes
        id: get_file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
        output: ' '
      - name: Echo file changes
        run: |
        echo Changed files: ${{ steps.get_file_changes.outputs.files }}
      - name: Lint changed files
        run: |
            pnpm biome ci ${{ steps.get_file_changes.outputs.files }}
      - name: Tests
        run: pnpm test
