name: Push checks
on: [push]
jobs:
  Checkout:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 9.*
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile
      - name: Biome Lint Changed Files
        run: |
          CHANGED_FILES=$(git diff --diff-filter=MA --name-only $(git merge-base origin/main ${{ github.ref_name }}) ${{ github.ref_name }})
          if [ "${{ github.ref_name }}" = "fix-biome-setup" ]; then
            echo "On main branch, skipping linting."
          elif [ -n "$CHANGED_FILES" ]; then
            pnpm biome ci $CHANGED_FILES --no-errors-on-unmatched
          else
            echo "No changed files to lint."
          fi
      - name: Tests
        run: pnpm test
